name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compailing reader_writer_multithread.c file
      run: gcc reader_writer_multithread.c -lpthread
    - name: testing
      run: ./a.out
